//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWCFServices.LINQBookHubEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_master
    {
        public stock_master()
        {
            this.stock_detail = new HashSet<stock_detail>();
        }
    
        public int code_value { get; set; }
        public string code_display { get; set; }
        public Nullable<decimal> rate { get; set; }
        public string uom { get; set; }
        public Nullable<decimal> closing { get; set; }
        public Nullable<decimal> opening { get; set; }
    
        public virtual ICollection<stock_detail> stock_detail { get; set; }
    }
}
