//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWCFServices.LINQBookHubEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_header
    {
        public tr_header()
        {
            this.stock_detail = new HashSet<stock_detail>();
        }
    
        public int doc_no { get; set; }
        public string Id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string narr { get; set; }
        public string @ref { get; set; }
    
        public virtual ICollection<stock_detail> stock_detail { get; set; }
    }
}
